<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magestore\Quotation\Block\Quote\Item\Renderer\DefaultRenderer $block */
$_item = $block->getItem();
$canShowPrice = $block->canShowPrice();
?>
<span <?php if($canShowPrice):?>class="price-excluding-tax"<?php endif;?> data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">
    <span class="cart-price">
        <?= /* @escapeNotVerified */ $block->getPrice($block->getItem()->getRowTotal()) ?>
    </span>
</span>
