<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magestore\Quotation\Block\Adminhtml\Product\Product\Form $block */
?>
<div id="quotation_product_create_form_html_container"
     class="hide">
    <form id="quotation_product_create_form_html">

        <div class="admin__field _required">
            <label class="admin__field-label"
                   for="new_product_name">
                <span><?= __("Product Name") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry"
                       type="text"
                       id="new_product_name"
                       name="product[name]"
                       maxlength="255"/>
            </div>
        </div>

        <div class="admin__field _required">
            <label class="admin__field-label"
                   for="new_product_sku">
                <span><?= __("SKU") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry"
                       type="text"
                       id="new_product_sku"
                       name="product[sku]"
                       maxlength="255"/>
            </div>
        </div>

        <div class="admin__field _required">
            <label class="admin__field-label"
                   for="new_product_price">
                <span><?= __("Price") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry validate-number"
                       type="text"
                       id="new_product_price"
                       name="product[price]"/>
            </div>
        </div>

        <div class="admin__field">
            <label class="admin__field-label"
                   for="new_product_description">
                <span><?= __("Description") ?></span>
            </label>
            <div class="admin__field-control">
            <textarea class="admin__control-textarea"
                      id="new_product_description"
                      name="product[description]"></textarea>
            </div>
        </div>

<!--        <div class="admin__field">-->
<!--            <label class="admin__field-label"-->
<!--                   for="new_product_image">-->
<!--                <span>--><?//= __("Product Image") ?><!--</span>-->
<!--            </label>-->
<!--            <div class="admin__field-control">-->
<!--                <input id="new_product_image"-->
<!--                       type="file"-->
<!--                       name="image"-->
<!--                       multiple="multiple" class=""/>-->
<!--            </div>-->
<!--        </div>-->
    </form>
</div>
