<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magestore\Quotation\Block\Adminhtml\Product\Product\Form $block */
?>
<div id="quotation_product_create_form_html_container"
     class="hide">
    <form id="quotation_product_create_form_html">

        <div class="admin__field _required">
            <label class="admin__field-label"
                   for="custom_product_name">
                <span><?= __("Product Name") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry"
                       type="text"
                       id="custom_product_name"
                       name="product[name]"
                       maxlength="255"/>
            </div>
        </div>

        <div class="admin__field _required">
            <label class="admin__field-label"
                   for="custom_product_price">
                <span><?= __("Price") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry validate-number"
                       type="text"
                       id="custom_product_price"
                       name="product[price]"/>
            </div>
        </div>

        <div class="admin__field">
            <label class="admin__field-label"
                   for="custom_product_weight">
                <span><?= __("Weight") ?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text validate-number"
                       type="text"
                       id="custom_product_weight"
                       name="product[weight]"/>
            </div>
        </div>
        
        <div class="admin__field">
            <label class="admin__field-label"
                   for="custom_product_tax_class">
                <span><?= __("Tax Class") ?></span>
            </label>
            <div class="admin__field-control">
                <select class="admin__control-select"
                        id="custom_product_tax_class"
                        name="product[tax_class_id]">
                    <?php foreach ($block->getTaxClasses() as $taxClass):?>
                        <option value="<?= $taxClass["value"]?>"><?= $taxClass["label"]?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>

        <div class="admin__field">
            <label class="admin__field-label"
                   for="custom_product_tax_class">
                <span><?= __("Shipable") ?></span>
            </label>
            <div class="admin__field-control">
                <select class="admin__control-select"
                        id="custom_product_tax_class"
                        name="product[is_virtual]">
                    <option value="0"><?= __("Yes")?></option>
                    <option value="1"><?= __("No")?></option>
                </select>
            </div>
        </div>

        <div class="admin__field">
            <label class="admin__field-label"
                   for="custom_product_description">
                <span><?= __("Description") ?></span>
            </label>
            <div class="admin__field-control">
            <textarea class="admin__control-textarea"
                      id="custom_product_description"
                      name="product[description]"></textarea>
            </div>
        </div>

<!--        <div class="admin__field">-->
<!--            <label class="admin__field-label"-->
<!--                   for="custom_product_image">-->
<!--                <span>--><?//= __("Product Image") ?><!--</span>-->
<!--            </label>-->
<!--            <div class="admin__field-control">-->
<!--                <input id="custom_product_image"-->
<!--                       type="file"-->
<!--                       name="image"-->
<!--                       multiple="multiple" class=""/>-->
<!--            </div>-->
<!--        </div>-->
    </form>
</div>
