<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magestore\Quotation\Block\Quote\Info */ ?>
<?php $_quote = $block->getQuote() ?>
<div class="block block-quote-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('QUOTE REQUEST') ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$_quote->getIsVirtual()): ?>
        <div class="box box-quote-shipping-address box-order-shipping-address">
            <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_quote->getShippingAddress()) ?></address>
            </div>
        </div>

        <div class="box box-quote-shipping-method box-order-shipping-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <?= /* @escapeNotVerified */ $block->getShippingMethodInfo() ?>
            </div>
        </div>
    <?php endif; ?>
    </div>
</div>
