<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magestore\Quotation\Block\Quote\View*/?>
<div class="quote-details-items">
    <?php $_quote = $block->getQuote() ?>

    <div class="quote-title">
        <strong><?= /* @escapeNotVerified */ __('Items Requested') ?></strong>
    </div>

    <?= $block->getChildHtml('quote_items') ?>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= /* @escapeNotVerified */ $block->getBackUrl() ?>">
                <span><?= /* @escapeNotVerified */ $block->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
