<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magestore\Quotation\Block\Quote\View*/?>
<ul class="items quote-links order-links"><li class="nav item current"><strong><?= /* @escapeNotVerified */ __('Items Requested') ?></strong></li></ul>
<div class="quote-details-items order-details-items">
    <?php $_quote = $block->getQuote() ?>
    <?= $block->getChildHtml('quote_items') ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= /* @escapeNotVerified */ $block->getBackUrl() ?>">
                <span><?= /* @escapeNotVerified */ $block->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
