<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magestore\Quotation\Block\Cart\Info\Address $block */
?>
<?php
$_company = $block->getCompanyWidget();
$_fax = $block->getFaxWidget();
$_telephone = $block->getTelephoneWidget();
?>

<fieldset class="fieldset" id="<?= $block->getContainerHtmlId()?>">
    <legend class="legend"><span><?= $block->escapeHtml($block->getHeaderTitle()) ?></span></legend>
    <br>

    <?= $block->getNameBlockHtml() ?>

    <?php if ($_company->isEnabled()): ?>
        <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
    <?php endif ?>

    <?php if ($_fax->isEnabled()): ?>
        <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
    <?php endif ?>

    <?php if ($_telephone->isEnabled()): ?>
        <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
    <?php endif ?>

    <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
    <div class="field street required">
        <label for="<?= $block->getAddressFieldId("street_1")?>" class="label">
            <span><?= $block->escapeHtml(__('Street Address')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   name="<?= $block->getAddressFieldName("street")?>[]"
                   value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                   id="<?= $block->getAddressFieldId("street_1")?>"
                   class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
            <div class="nested">
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++):
                    $streetFieldNumber = $_i + 1;
                    ?>
                    <div class="field additional">
                        <label class="label" for="<?= $block->getAddressFieldId("street_$streetFieldNumber")?>">
                            <span><?= $block->escapeHtml(__('Street Address %1', $streetFieldNumber)) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="<?= $block->getAddressFieldName("street")?>[]"
                                   value="<?= $block->escapeHtmlAttr($block->getStreetLine($streetFieldNumber)) ?>"
                                   title="<?= $block->escapeHtmlAttr(__('Street Address %1', $streetFieldNumber)) ?>"
                                   id="<?= $block->getAddressFieldId("street_$streetFieldNumber")?>"
                                   class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                        </div>
                    </div>
                <?php endfor; ?>
            </div>
        </div>
    </div>

    <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
        <div class="field taxvat">
            <label class="label" for="<?= $block->getAddressFieldId("vat_id")?>">
                <span><?= $block->escapeHtml(__('VAT Number')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="<?= $block->getAddressFieldName("vat_id")?>"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                       id="<?= $block->getAddressFieldId("vat_id")?>">
            </div>
        </div>
    <?php endif; ?>
    <div class="field city required">
        <label class="label" for="<?= $block->getAddressFieldId("city")?>"><span><?= $block->escapeHtml(__('City')) ?></span></label>
        <div class="control">
            <input type="text"
                   name="<?= $block->getAddressFieldName("city")?>"
                   value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                   class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                   id="<?= $block->getAddressFieldId("city")?>">
        </div>
    </div>
    <div class="field region required">
        <label class="label" for="<?= $block->getAddressFieldId("region_id")?>">
            <span><?= $block->escapeHtml(__('State/Province')) ?></span>
        </label>
        <div class="control">
            <select id="<?= $block->getAddressFieldId("region_id")?>" name="<?= $block->getAddressFieldName("region_id")?>"
                    title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                    class="validate-select" <?= /* @noEscape */
            !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
            </select>
            <input type="text"
                   id="<?= $block->getAddressFieldId("region")?>"
                   name="<?= $block->getAddressFieldName("region")?>"
                   value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                   class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
        </div>
    </div>
    <div class="field zip required">
        <label class="label" for="<?= $block->getAddressFieldId("zip")?>">
            <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   name="<?= $block->getAddressFieldName("postcode")?>"
                   value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                   id="<?= $block->getAddressFieldId("zip")?>"
                   class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
        </div>
    </div>
    <div class="field country required">
        <label class="label" for="<?= $block->getAddressFieldId("country")?>"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
        <div class="control">
            <?= $block->getCountryHtmlSelect(null, $block->getAddressFieldName("country_id"), $block->getAddressFieldId("country")) ?>
        </div>
    </div>
    <?php if($block->isBillingAddress() && !$block->isVirtual()):?>
    <div class="field use_for_shipping">
        <div class="control">
            <input type="checkbox"
                   name="shipping[same_as_billing]"
                   value="1"
                   title="<?= $block->escapeHtmlAttr(__('Use Same Address For Shipping')) ?>"
                   id="<?= $block->getAddressFieldId("use_for_shipping")?>"
                   <?php echo ($block->isShippingSameAsBilling())?"checked":"";?>
                   class="input-checkbox">
            <label class="label" for="<?= $block->getAddressFieldId("use_for_shipping")?>"><span><?= $block->escapeHtml(__('Use Same Address For Shipping')) ?></span></label>
        </div>
    </div>
    <script>
        require(["jquery"], function($){
            var shippingAddressContainerEl = $("#shipping_address_container");
            var useForShippingEl = $("#<?= $block->getAddressFieldId("use_for_shipping")?>");
            if(useForShippingEl.length > 0){
                if(useForShippingEl.is(':checked')){
                    shippingAddressContainerEl.hide();
                }else{
                    shippingAddressContainerEl.show();
                }
                useForShippingEl.change(function() {
                    if(this.checked) {
                        shippingAddressContainerEl.hide();
                    }else{
                        shippingAddressContainerEl.show();
                    }
                });
            }
        });
    </script>
    <?php endif;?>
</fieldset>
<script type="text/x-magento-init">
    {
        "#quotation-info-form": {
            "addressValidation": {}
        },
        "#<?= $block->getAddressFieldId("country")?>": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */
    $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#<?= $block->getAddressFieldId("region_id")?>",
                "regionInputId": "#<?= $block->getAddressFieldId("region")?>",
                "postcodeId": "#<?= $block->getAddressFieldId("zip")?>",
                "form": "quotation-info-form",
                "regionJson": <?= /* @noEscape */
    $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */
    $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }


</script>
