<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magestore\Quotation\Block\Cart\Info */
?>
<form action="<?php echo $block->getSubmitUrl();?>"
      method="post"
      id="quotation-info-form"
      class="quotation-info-form form form-cart form-address-edit"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

    <?php echo $block->getChildHtml("quotation.cart.info.address");?>
    <div class="cart main actions">
        <button type="button"
                title="<?php echo $block->getSubmitButtonTitle();?>"
                class="action primary submit">
            <span><?php echo $block->getSubmitButtonTitle();?></span>
        </button>
    </div>
</form>
<script>
    require([
        'jquery',
        'Magestore_Quotation/js/model/quote/form'
    ], function($){
        if(($("#quotation-info-form").length > 0) && ($("#form-validate").length > 0)){
            quoteRequest.itemsOnchangeBind();
            $("#quotation-info-form").find("button.submit").click(function(){
                quoteRequest.submit();
            });
        }
    });
</script>