<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magestore\Quotation\Block\Adminhtml\Quote\Edit\Items\Grid
 */
?>

<?php
$canEdit = $block->canEdit();
$_items = $block->getItems();
?>
<?php if (empty($_items)): ?>
    <div id="quote-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary quote-tables">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                        <th class="col-price"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                        <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                        <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                        <th class="col-discount"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                        <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                        <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?= /* @escapeNotVerified */ __('No ordered items') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <div class="admin__table-wrapper" id="quote-items_grid">
    <?php if ($canEdit && (count($_items)>10)): ?>
        <div class="actions update actions-update">
            <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
        </div>
    <?php endif; ?>
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <th class="col-remark"><span><?= /* @escapeNotVerified */ __('Remark') ?></span></th>
                    <th class="col-price"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                    <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                    <th class="col-discount"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                    <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                    <?php if($canEdit):?>
                    <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-total"><?= /* @escapeNotVerified */ __('Total %1 product(s)', count($_items)) ?></td>
                    <td class="col-price"></td>
                    <td colspan="2" class="col-subtotal"><?= /* @escapeNotVerified */ __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <td class="col-price"><strong>
                    <?php
                        /* @escapeNotVerified */ echo $block->formatPrice($block->getSubtotalWithDiscount());
                    ?></strong></td>
                    <?php if($canEdit):?>
                    <td colspan="2">&nbsp;</td>
                    <?php endif; ?>
                </tr>
            </tfoot>
                <?php $i = 0 ?>
                <?php foreach ($_items as $_item):$i++ ?>
                <tbody class="<?= /* @escapeNotVerified */ ($i%2) ? 'even' : 'odd' ?>">
                    <tr>
                        <td class="col-product">
                            <span id="order_item_<?= /* @escapeNotVerified */ $_item->getId() ?>_title"><?= $block->escapeHtml($_item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                            </div>
                            <?php if ($_options = $block->getItemOptions($_item)): ?>
                                <dl class="product-options-block">
                                    <?php foreach ($_options as $_option) : ?>
                                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                        <dd>
                                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                            <?php else: ?>
                                                <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                            <?php endif; ?>
                                        </dd>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                        </td>
                        <td class="col-remark">
                            <?= $_item->getAdditionalData() ?>
                        </td>
                        <td class="col-price">

                            <?= $block->getItemUnitPriceHtml($_item) ?>

                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($_tier = $block->getTierHtml($_item)): ?>
                            <div id="item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
                                <a href="#" onclick="$('item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>').toggle();return false;"><?= /* @escapeNotVerified */ __('Tier Pricing') ?></a>
                                <div style="display:none" id="item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>"><?= /* @escapeNotVerified */ $_tier ?></div>
                            </div>
                            <?php endif; ?>
                            <?php if ($block->canApplyCustomPrice($_item)): ?>
                                <div class="custom-price-block">
                                    <input type="checkbox"
                                           class="admin__control-checkbox"
                                           id="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                           <?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?>
                                           <?php if (!$canEdit): ?>disabled<?php endif;?>
                                           onclick="quote.toggleCustomPrice(this, 'item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>', 'item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>');"/>
                                    <label
                                        class="normal admin__field-label"
                                        for="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>">
                                        <span><?= /* @escapeNotVerified */ __('Custom Price') ?>*</span></label>
                                </div>
                            <?php endif; ?>
                            <input id="item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                   name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][custom_price]"
                                   value="<?= /* @escapeNotVerified */ sprintf("%.2f", $block->getOriginalEditablePrice($_item)) ?>"
                                   <?php if (!$_isCustomPrice): ?>
                                   style="display:none"
                                   <?php endif; ?>
                                   <?php if (!$_isCustomPrice || !$canEdit): ?>
                                   disabled="disabled"
                                   <?php endif; ?>
                                   class="input-text item-price admin__control-text"/>
                        </td>
                        <td class="col-qty">
                            <input name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                   class="input-text item-qty admin__control-text"
                                   value="<?= /* @escapeNotVerified */ $_item->getQty()*1 ?>"
                                    <?php if (!$canEdit): ?>disabled<?php endif;?>
                                   maxlength="12" />
                        </td>
                        <td class="col-subtotal col-price">
                            <?= $block->getItemRowTotalHtml($_item) ?>
                        </td>
                        <td class="col-discount col-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice(-$_item->getTotalDiscountAmount()) ?>
                       </td>
                        <td class="col-price col-row-subtotal">
                            <?= $block->getItemRowTotalWithDiscountHtml($_item) ?>
                        </td>
                        <?php if ($canEdit): ?>
                        <td class="col-actions last">
                            <select class="admin__control-select" name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][action]">
                                <option value=""><?= /* @escapeNotVerified */ __('Please select') ?></option>
                                <option value="remove"><?= /* @escapeNotVerified */ __('Remove') ?></option>
                            </select>
                        </td>
                        <?php endif;?>
                    </tr>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($_item->getMessage(false) as $messageError):?>
                        <?php if (!empty($messageError)) {
                            $hasMessageError = true;
                        }
                        ?>
                    <?php endforeach; ?>

                    <?php if ($hasMessageError):?>
                        <tr class="row-messages-error">
                            <td colspan="100"> <!-- ToDo UI: remove the 100 -->
                                <?php foreach ($_item->getMessage(false) as $message):
                                    if (empty($message)) {
                                        continue;
                                    }
                                    ?>
                                    <div class="message <?php if ($_item->getHasError()): ?>message-error<?php else: ?>message-notice<?php endif; ?>">
                                        <?= $block->escapeHtml($message) ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif;?>
                </tbody>
                <?php endforeach; ?>
        </table>
        <?php if($canEdit):?>
        <p><small><?= /* @escapeNotVerified */ $block->getInclExclTaxMessage() ?></small></p>
        <?php endif;?>
    </div>
    <?php if($canEdit):?>
    <div class="quote-discounts">
        <?= $block->getButtonHtml(__('Create New Product'), 'product.showCreateForm()', 'action-secondary') ?>
        <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
    </div>
    <script>
        require([
            'Magestore_Quotation/js/model/quote/form'
        ], function(){
            quote.itemsOnchangeBind()
        });
    </script>
    <?php endif;?>
<?php endif; ?>
