<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magestore\Quotation\Block\Quote\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
?>
<tr id="quote-item-row-<?= /* @escapeNotVerified */ $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <a href="<?php echo $_item->getProduct()->getUrlInStore();?>"><strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong></a>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                    <?php else: ?>
                        <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @escapeNotVerified */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col remark" data-th="<?= $block->escapeHtml(__('Remark')) ?>"><?= /* @escapeNotVerified */ $block->getItem()->getAdditionalData() ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price Proposal')) ?>">
        <?= $block->getItemPriceHtml($_item) ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <?= /* @escapeNotVerified */ $block->getItem()->getQty()*1 ?>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
