<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 ?>

<?php /* <h4 class="icon-head fieldset-legend <?= $block->getHeaderCssClass() ?>"><?= $block->getHeaderText() ?></h4> */ ?>
<div class="admin__field field-comment">
    <label for="quote-comment" class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Quote Comments') ?></span></label>
    <div class="admin__field-control">
        <textarea
            id="quote-comment"
            name="quote[comment][customer_note]"
            class="admin__control-textarea"><?= /* @escapeNotVerified */ $block->getCommentNote() ?></textarea>
    </div>
</div>
<script>
    require(["Magestore_Quotation/js/model/quote/form"], function(){
        // quote.commentFieldsBind('quote-comment')
    });
</script>
