<?php
/**
 * Copyright © Magestore, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="page-edit-quote">
    <script>
    require(["Magestore_Quotation/js/model/quote/form"], function(){
        quote.setCurrencySymbol('<?= /* @escapeNotVerified */ $block->getCurrencySymbol($block->getCurrentCurrencyCode()) ?>')
    });
</script>
    <div class="quote-details">
        <div id="quote-search" style="display: none" class="admin__page-section quote-search-items order-search-items">
            <?= $block->getChildHtml('search') ?>
        </div>
        <section id="quote-items" class="admin__page-section quote-items" data-mage-init='{"loader": {}}'>
            <?= $block->getChildHtml('items') ?>
        </section>

        <div id="quote-errors" class="quote-errors"><?= $block->getChildHtml('errors') ?></div>

        <section class="admin__page-section quote-summary">
            <div class="admin__page-section-title">
            </div>
            <div class="admin__page-section-content">
                <div class="admin__page-section-item quote-comments-history order-comments-history">
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= __("Notes for this Order")?></span>
                    </div>
                    <?= $block->getChildHtml('comment') ?>
                </div>
                <div id="quote-shipping_method" class="admin__page-section-item quote-shipping-method order-shipping-method">
                    <?= $block->getChildHtml('shipping_method') ?>
                </div>
                <fieldset id="quote-totals" class="admin__fieldset quote-totals order-totals">
                    <?= $block->getChildHtml('totals') ?>
                </fieldset>
            </div>
        </section>
    </div>

</div>
